# Generated by Django 5.0.14 on 2026-08-01 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only Latin letters are allowed (no numbers or special characters)..",
                        regex="^[A-Za-z\\-]+$",
                    )
                ],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("uk", "Українська"),
                    ("pl", "Polski"),
                    ("en", "English"),
                    ("ru", "Русский"),
                ],
                default="uk",
                max_length=2,
                verbose_name="Interface language",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only Latin letters are allowed (no numbers or special characters)..",
                        regex="^[A-Za-z\\-]+$",
                    )
                ],
                verbose_name="Surname",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Phone number"
            ),
        ),
    ]
