# Generated by Django 5.0.14 on 2026-08-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbsenceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("dayoff", "Вихідний день"),
                            ("l4", "Лікарняний (L4)"),
                        ],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата початку")),
                ("end_date", models.DateField(verbose_name="Дата закінчення")),
                (
                    "days_count",
                    models.PositiveIntegerField(verbose_name="Кількість днів"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує"),
                            ("approved", "Підтверджено"),
                            ("rejected", "Відхилено"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата рішення"
                    ),
                ),
                (
                    "notified_coordinator_message_ids",
                    models.JSONField(blank=True, default=dict),
                ),
            ],
            options={
                "verbose_name": "Зголошення",
                "verbose_name_plural": "Зголошення",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Назва проєкту"),
                ),
                (
                    "dayoff_limit",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Максимальна кількість вихідних днів, яку можна обрати в одному зголошенні.",
                        verbose_name="Ліміт днів (вихідні)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проєкт",
                "verbose_name_plural": "Проєкти",
                "ordering": ["region__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectEmailRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("to", "Прямий отримувач (To)"),
                            ("cc", "Копія (DW/CC)"),
                        ],
                        default="to",
                        max_length=2,
                        verbose_name="Тип надсилання",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email-отримувач проєкту",
                "verbose_name_plural": "Email-отримувачі проєктів",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Назва регіону"
                    ),
                ),
            ],
            options={
                "verbose_name": "Регіон",
                "verbose_name_plural": "Регіони",
                "ordering": ["name"],
            },
        ),
    ]
