# Generated by Django 5.0.14 on 2026-08-01 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="absencerequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Хто прийняв рішення",
            ),
        ),
        migrations.AddField(
            model_name="absencerequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Працівник",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="coordinators",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_staff": True},
                related_name="coordinated_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Відповідальні координатори",
            ),
        ),
        migrations.AddField(
            model_name="absencerequest",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="core.project",
                verbose_name="Проєкт",
            ),
        ),
        migrations.AddField(
            model_name="projectemailrecipient",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_recipients",
                to="core.project",
                verbose_name="Проєкт",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="core.region",
                verbose_name="Регіон",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "region")},
        ),
    ]
