# Generated by Django 5.0.14 on 2026-08-01 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="absencerequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Reporting",
                "verbose_name_plural": "Reporting",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["region__name", "name"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="projectemailrecipient",
            options={
                "verbose_name": "Project email recipient",
                "verbose_name_plural": "Project email recipients",
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={
                "ordering": ["name"],
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.AddField(
            model_name="absencerequest",
            name="dates",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Selected dates (ISO)"
            ),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="days_count",
            field=models.PositiveIntegerField(verbose_name="Number of days"),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="decided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date of decision"
            ),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Who made the decision?",
            ),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="end_date",
            field=models.DateField(verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="core.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="request_type",
            field=models.CharField(
                choices=[("dayoff", "Day off"), ("l4", "Sick day (L4)")],
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="start_date",
            field=models.DateField(verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Worker",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="coordinators",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_staff": True},
                related_name="coordinated_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible coordinators",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="dayoff_limit",
            field=models.PositiveIntegerField(
                default=5,
                help_text="The maximum total number of days off an employee can take for this project in a single calendar month (taking into account all their requests for that month, excluding rejected ones).",
                verbose_name="Monthly limit of days off",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Project name"),
        ),
        migrations.AlterField(
            model_name="project",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="core.region",
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="projectemailrecipient",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_recipients",
                to="core.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="projectemailrecipient",
            name="recipient_type",
            field=models.CharField(
                choices=[("to", "Direct recipient (To)"), ("cc", "Copy (DW/CC)")],
                default="to",
                max_length=2,
                verbose_name="Sending type",
            ),
        ),
    ]
