# Generated by Django 5.0.14 on 2026-08-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_absencerequest_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="max_workers_per_day",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="The maximum number of employees on this project who can be off on the same day. Leave blank for no limit (default).",
                null=True,
                verbose_name="Employee limit as of the date (blank) - no restrictions (default).",
            ),
        ),
    ]
