# Generated by Django 5.0.14 on 2026-08-01 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_max_workers_per_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "max_workers",
                    models.PositiveIntegerField(
                        verbose_name="Ліміт працівників на цю дату"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_limits",
                        to="core.project",
                        verbose_name="Проєкт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ліміт працівників на дату",
                "verbose_name_plural": "Ліміти працівників на конкретні дати",
                "ordering": ["date"],
                "unique_together": {("project", "date")},
            },
        ),
    ]
