# Generated by Django 5.0.14 on 2026-08-01 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_projectdatelimit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectdatelimit",
            options={
                "ordering": ["date"],
                "verbose_name": "Employee limit for this date",
                "verbose_name_plural": "Staffing limits for specific dates",
            },
        ),
        migrations.AlterField(
            model_name="projectdatelimit",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="projectdatelimit",
            name="max_workers",
            field=models.PositiveIntegerField(
                verbose_name="Employee limit for this date"
            ),
        ),
        migrations.AlterField(
            model_name="projectdatelimit",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date_limits",
                to="core.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Region name"
            ),
        ),
    ]
