# Generated by Django 5.0.14 on 2026-08-21 16:10

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_projectdatelimit_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Name (for the admin panel)"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text='Supports emojis and basic Telegram HTML formatting: <b>bold</b>, <i>italics</i>, <a href="...">link</a>.',
                        verbose_name="Message text",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Усі активні користувачі"),
                            ("specific", "Обрані користувачі"),
                        ],
                        default="all",
                        max_length=10,
                        verbose_name="Recipients",
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "Немає (одноразово)"),
                            ("daily", "Щодня"),
                            ("weekly", "Щотижня"),
                            ("monthly", "Щомісяця"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Repetition",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date and time of departure (for a one-time trip)",
                    ),
                ),
                (
                    "send_time",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Departure time (for scheduled flights)",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Понеділок"),
                            (1, "Вівторок"),
                            (2, "Середа"),
                            (3, "Четвер"),
                            (4, "П'ятниця"),
                            (5, "Субота"),
                            (6, "Неділя"),
                        ],
                        null=True,
                        verbose_name="Day of the week (for “Every Week”)",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="If a month has fewer days (e.g., 31 in February), it will be sent on the last day of the month.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Month number (for “Monthly”)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last sent"
                    ),
                ),
                (
                    "last_sent_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sent successfully (last time)"
                    ),
                ),
                (
                    "last_failed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Mistakes (for the last time)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "specific_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Fill this out only if “Selected users” is selected above.",
                        related_name="broadcasts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Selected users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Newsletters",
                "ordering": ["-created_at"],
            },
        ),
    ]
