# Generated by Django 5.0.14 on 2026-08-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_broadcast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="audience",
            field=models.CharField(
                choices=[("all", "All active users"), ("specific", "Selected Users")],
                default="all",
                max_length=23,
                verbose_name="Recipients",
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none”, “None (one-time)", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none”, “None (one-time)",
                max_length=23,
                verbose_name="Repetition",
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                null=True,
                verbose_name="Day of the week (for “Every Week”)",
            ),
        ),
    ]
