# Generated by Django 5.0.14 on 2026-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_broadcast_audience_alter_broadcast_recurrence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="text",
            field=models.TextField(
                help_text="Supports emojis and basic Telegram HTML formatting: <b>bold</b>, <i>italics</i>",
                verbose_name="Message text",
            ),
        ),
    ]
