# Generated by Django 5.0.14 on 2026-08-30 17:39

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_broadcast_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('administration', 'Administration'), ('accounting', 'Accounting Department')], max_length=20, verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Text of the request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('decision_token', models.CharField(default=core.models.generate_decision_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporting to Administration/Accounting',
                'verbose_name_plural': 'Reporting to Administration/Accounting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('administration', 'Administration'), ('accounting', 'Accounting Department')], max_length=20, verbose_name='Department')),
                ('recipient_type', models.CharField(choices=[('to', 'Direct recipient (To)'), ('cc', 'Copy (DW/CC)')], default='to', max_length=2, verbose_name='Sending type')),
                ('user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='department_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='Person in charge')),
            ],
            options={
                'verbose_name': 'Department contact person',
                'verbose_name_plural': 'Departmental points of contact',
                'unique_together': {('department', 'user', 'recipient_type')},
            },
        ),
    ]
